"""FFmpeg-backed HLS transcoder adapter.

The adapter spins up one ffmpeg process per playback session. Encoding
runs in the background and writes MPEG-TS segments named
``segment_NNNNN.ts`` to the session's output directory. The HLS
playlist that the *client* consumes (``index.m3u8``) is pre-written by
the application layer once the source's total duration is known — we
deliberately have ffmpeg write its own playlist to a sentinel file
(``_ffmpeg.m3u8``) and ignore it so we can support arbitrary seeking
without the playlist growing piecewise.

To make user seeks land instantly, the application layer can call
:meth:`ensure_hls_session` again with ``start_segment_index=N``. We
then terminate the current ffmpeg process and spawn a new one that
input-seeks to ``N * segment_seconds`` and resumes segment numbering at
``N``. ``-copyts`` keeps PTS continuous with the canonical playlist so
the player can splice from any previous segment to the new ones
without an ``#EXT-X-DISCONTINUITY`` marker.
"""

from __future__ import annotations

import json
import logging
import math
import os
import shutil
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path

from domain.errors import InfrastructureError

_LOG = logging.getLogger(__name__)


@dataclass(slots=True)
class _ActiveTranscode:
    session_id: str
    output_dir: str
    manifest_path: str
    process: subprocess.Popen[bytes]
    started_at: float
    start_segment_index: int
    segment_seconds: int
    source_path: str
    audio_track: int | None
    subtitle_track: int | None


class FFmpegTranscoderAdapter:
    """Materialize HLS artifacts using one ffmpeg process per session."""

    # ffmpeg writes its own playlist to this name inside the session
    # directory. We never serve this file; the canonical playlist that
    # the client receives (``index.m3u8``) is generated by the
    # application layer once the source duration is known.
    _FFMPEG_PLAYLIST_NAME = "_ffmpeg.m3u8"
    # Per-session ffmpeg stderr is mirrored here so a failed transcode
    # leaves behind a forensic trail without polluting the process
    # stdout. The file is opened in append mode; restarts share it.
    _FFMPEG_LOG_NAME = "_ffmpeg.log"

    def __init__(
        self,
        *,
        ffmpeg_bin: str = "ffmpeg",
        ffprobe_bin: str = "ffprobe",
        max_active_sessions: int = 2,
        segment_seconds: int = 4,
        startup_timeout_seconds: int = 15,
    ) -> None:
        self._ffmpeg_bin = ffmpeg_bin
        self._ffprobe_bin = ffprobe_bin
        self._max_active_sessions = max(1, int(max_active_sessions))
        self._segment_seconds = max(2, int(segment_seconds))
        self._startup_timeout_seconds = max(3, int(startup_timeout_seconds))
        self._active: dict[str, _ActiveTranscode] = {}
        self._lock = threading.RLock()

    # ------------------------------------------------------------------
    # MediaTranscoderPort
    # ------------------------------------------------------------------

    def ensure_hls_session(
        self,
        *,
        session_id: str,
        source_path: str,
        output_dir: str,
        audio_track: int | None = None,
        subtitle_track: int | None = None,
        start_segment_index: int = 0,
        segment_seconds: int | None = None,
        duration_seconds: float | None = None,
    ) -> dict[str, str]:
        ffmpeg_cmd = shutil.which(self._ffmpeg_bin) or self._ffmpeg_bin
        seg_secs = (
            int(segment_seconds)
            if segment_seconds is not None
            else self._segment_seconds
        )
        seg_secs = max(2, seg_secs)
        start_index = max(0, int(start_segment_index))
        probed_duration = 0.0
        if duration_seconds is not None:
            try:
                probed_duration = max(0.0, float(duration_seconds))
            except (TypeError, ValueError):
                probed_duration = 0.0
        if probed_duration > 0:
            max_start = max(0, math.ceil(probed_duration / seg_secs) - 1)
            start_index = min(start_index, max_start)
        manifest_path = str(Path(output_dir) / "index.m3u8")
        ffmpeg_playlist = str(Path(output_dir) / self._FFMPEG_PLAYLIST_NAME)
        # When the application layer has pre-written ``index.m3u8`` we
        # must not let ffmpeg touch it — its hls muxer would clobber
        # the carefully-crafted full segment list. We also need to
        # avoid the canonical playlist whenever we're restarting mid-
        # stream (``start_index > 0``). Everything else (the original
        # "live" code path where nobody pre-wrote a manifest) keeps
        # the legacy behaviour: ffmpeg owns ``index.m3u8`` directly.
        caller_owns_playlist = os.path.isfile(manifest_path) or start_index > 0
        ffmpeg_target_playlist = (
            ffmpeg_playlist if caller_owns_playlist else manifest_path
        )

        with self._lock:
            self._reap_finished_locked()
            existing = self._active.get(session_id)
            if (
                existing is not None
                and existing.process.poll() is None
                and existing.start_segment_index == start_index
                and existing.segment_seconds == seg_secs
                and existing.audio_track == audio_track
            ):
                return {
                    "manifest_path": existing.manifest_path,
                    "output_dir": existing.output_dir,
                    "start_segment_index": str(existing.start_segment_index),
                    "segment_seconds": str(existing.segment_seconds),
                }
            # Tear down a divergent process before launching a new one
            # so that two ffmpeg instances don't fight over the same
            # output directory. This is what makes "seek beyond the
            # current encode head" possible.
            purge_segments = False
            if existing is not None:
                # A later encode that started further into the file leaves
                # ``segment_NNNNN.ts`` files whose timestamps align with that
                # offset. If we restart ffmpeg *earlier* (common when the
                # player prefetches segment 0 while the session was started
                # mid-file from a resume hint), those high-index segments
                # become stale: their PTS no longer matches the new low
                # segments and Shaka aborts with a generic decode error.
                # Different audio or segment length also invalidates every
                # existing transport stream.
                if (
                    start_index < existing.start_segment_index
                    or audio_track != existing.audio_track
                    or seg_secs != existing.segment_seconds
                ):
                    purge_segments = True
                self._terminate(existing.process)
                self._active.pop(session_id, None)
            while len(self._active) >= self._max_active_sessions:
                if not self._evict_oldest_locked(excluding=session_id):
                    raise InfrastructureError(
                        "Media server is busy: too many active transcoding sessions."
                    )

            os.makedirs(output_dir, exist_ok=True)
            if purge_segments:
                self._purge_ts_segments(output_dir)
            # The HLS muxer's ``append_list`` flag refuses to truncate
            # an existing playlist file, which on a seek-on-demand
            # restart leaves behind stale entries from the previous
            # encode. Removing the sentinel up front gives ffmpeg a
            # clean slate and avoids the muxer hanging while trying
            # to merge incompatible playlist states.
            self._clear_stale_ffmpeg_artifacts(
                ffmpeg_playlist=ffmpeg_playlist,
                output_dir=output_dir,
            )
            log_path = str(Path(output_dir) / self._FFMPEG_LOG_NAME)
            command = self._build_command(
                ffmpeg_cmd=ffmpeg_cmd,
                source_path=source_path,
                playlist_output=ffmpeg_target_playlist,
                output_dir=output_dir,
                audio_track=audio_track,
                subtitle_track=subtitle_track,
                start_segment_index=start_index,
                segment_seconds=seg_secs,
                duration_seconds=probed_duration,
            )
            _LOG.info(
                "ffmpeg_spawn source=%s start_seg=%s audio=%s subtitle=%s cmd=%s",
                source_path,
                start_index,
                audio_track,
                subtitle_track,
                " ".join(command),
            )
            self._write_spawn_record(log_path, command)
            process = self._spawn_ffmpeg(command, log_path)
            self._active[session_id] = _ActiveTranscode(
                session_id=session_id,
                output_dir=output_dir,
                manifest_path=manifest_path,
                process=process,
                started_at=time.time(),
                start_segment_index=start_index,
                segment_seconds=seg_secs,
                source_path=source_path,
                audio_track=audio_track,
                subtitle_track=None,
            )
            _LOG.info(
                "transcode_started session=%s active=%s source=%s start_seg=%s subs=%s log=%s",
                session_id,
                len(self._active),
                source_path,
                start_index,
                None,
                log_path,
            )

        # If the application layer pre-wrote ``index.m3u8`` we can
        # return immediately — the client only needs the manifest,
        # not the first segment. Otherwise, we keep the legacy
        # behaviour of blocking until ffmpeg has produced ``index.m3u8``
        # so the client has something to load.
        if not os.path.isfile(manifest_path):
            self._wait_for_initial_manifest(
                session_id=session_id,
                process=process,
                manifest_path=manifest_path,
            )

        return {
            "manifest_path": manifest_path,
            "output_dir": output_dir,
            "start_segment_index": str(start_index),
            "segment_seconds": str(seg_secs),
            "log_path": log_path,
            "effective_subtitle_track": "",
        }

    def stop_hls_session(self, session_id: str) -> None:
        with self._lock:
            active = self._active.pop(session_id, None)
        if active is None:
            return
        self._terminate(active.process)
        _LOG.info("transcode_stopped session=%s", session_id)

    def is_hls_session_running(self, session_id: str) -> bool:
        with self._lock:
            self._reap_finished_locked()
            active = self._active.get(session_id)
            return active is not None and active.process.poll() is None

    def probe_media_tracks(self, source_path: str) -> dict[str, list[dict[str, object]]]:
        ffprobe_cmd = shutil.which(self._ffprobe_bin) or self._ffprobe_bin
        command = [
            ffprobe_cmd,
            "-v",
            "error",
            "-show_entries",
            "stream=index,codec_type,codec_name:stream_tags=language,title",
            "-of",
            "json",
            source_path,
        ]
        try:
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
                timeout=15,
            )
            payload = json.loads(result.stdout or "{}")
            streams = list(payload.get("streams") or [])
        except Exception:
            return {"audio": [], "subtitles": []}

        audio: list[dict[str, object]] = []
        subtitles: list[dict[str, object]] = []
        audio_pos = 0
        sub_pos = 0
        for stream in streams:
            kind = str(stream.get("codec_type") or "")
            tags = stream.get("tags") or {}
            lang = str(tags.get("language") or "und")
            title = str(tags.get("title") or "").strip()
            label = f"{lang.upper()}"
            if title:
                label = f"{label} · {title}"
            if kind == "audio":
                audio.append({"id": audio_pos, "label": label})
                audio_pos += 1
            elif kind == "subtitle":
                codec_raw = str(stream.get("codec_name") or "").strip().lower()
                subtitles.append({"id": sub_pos, "label": label, "codec": codec_raw})
                sub_pos += 1
        return {"audio": audio, "subtitles": subtitles}

    def probe_media_duration(self, source_path: str) -> float:
        """Return the duration of ``source_path`` in seconds.

        We try the container-level ``format=duration`` first, then fall
        back to the longest stream duration. Returns ``0.0`` when the
        duration is not available — the caller is expected to drop back
        to a live-style playlist when that happens.
        """
        ffprobe_cmd = shutil.which(self._ffprobe_bin) or self._ffprobe_bin
        command = [
            ffprobe_cmd,
            "-v",
            "error",
            "-show_entries",
            "format=duration:stream=duration",
            "-of",
            "json",
            source_path,
        ]
        try:
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
                timeout=15,
            )
            payload = json.loads(result.stdout or "{}")
        except Exception:
            return 0.0

        def _as_float(value: object) -> float:
            try:
                f = float(value)  # type: ignore[arg-type]
            except (TypeError, ValueError):
                return 0.0
            if f != f:  # NaN guard
                return 0.0
            return max(0.0, f)

        fmt_dur = _as_float((payload.get("format") or {}).get("duration"))
        if fmt_dur > 0:
            return fmt_dur
        stream_durations = [
            _as_float(stream.get("duration"))
            for stream in (payload.get("streams") or [])
        ]
        return max(stream_durations, default=0.0)

    # ------------------------------------------------------------------
    # Implementation details
    # ------------------------------------------------------------------

    def _reap_finished_locked(self) -> None:
        for session_id, active in list(self._active.items()):
            if active.process.poll() is not None:
                code = active.process.returncode
                _LOG.warning(
                    "transcode_exited session=%s code=%s start_seg=%s source=%s",
                    session_id,
                    code,
                    active.start_segment_index,
                    active.source_path,
                )
                self._log_exit_footer(active.output_dir, code)
                self._active.pop(session_id, None)

    def _evict_oldest_locked(self, *, excluding: str) -> bool:
        """Stop the least-recently-started session to make room for a new encode.

        Called with ``self._lock`` held. Returns ``False`` when every active
        session is ``excluding`` (should not happen in practice).
        """
        candidates = [
            (sid, active)
            for sid, active in self._active.items()
            if sid != excluding
        ]
        if not candidates:
            return False
        victim_id, victim = min(candidates, key=lambda item: item[1].started_at)
        _LOG.warning(
            "transcode_evicted victim=%s for incoming=%s active=%s",
            victim_id,
            excluding,
            len(self._active),
        )
        self._terminate(victim.process)
        self._active.pop(victim_id, None)
        return True

    @staticmethod
    def _log_exit_footer(output_dir: str, exit_code: int | None) -> None:
        log_path = Path(output_dir) / FFmpegTranscoderAdapter._FFMPEG_LOG_NAME
        try:
            with open(log_path, "ab") as fh:
                fh.write(
                    f"\n[AnimeManager] ffmpeg exited with code {exit_code}\n".encode(
                        "utf-8",
                        errors="replace",
                    )
                )
        except OSError:
            pass

    def _build_command(
        self,
        *,
        ffmpeg_cmd: str,
        source_path: str,
        playlist_output: str,
        output_dir: str,
        audio_track: int | None,
        subtitle_track: int | None,
        start_segment_index: int,
        segment_seconds: int,
        duration_seconds: float = 0.0,
    ) -> list[str]:
        segment_pattern = str(Path(output_dir) / "segment_%05d.ts")
        # Input-seek to N*seg_secs so that ffmpeg's first emitted segment
        # corresponds to the requested playlist position. ``-copyts``
        # keeps PTS values aligned with the canonical playlist time so
        # the player can splice from any previous segment to the new
        # ones without an ``#EXT-X-DISCONTINUITY`` marker.
        seek_seconds = start_segment_index * segment_seconds
        if duration_seconds > 0:
            # Avoid landing past EOF when ffprobe over-estimates duration.
            seek_seconds = min(seek_seconds, max(0.0, duration_seconds - segment_seconds))
        command: list[str] = [
            ffmpeg_cmd,
            "-hide_banner",
            "-loglevel",
            "error",
            "-nostdin",
            "-y",
            "-fflags",
            "+genpts",
        ]
        if seek_seconds > 0:
            # When the user has selected a burnt-in subtitle track we
            # can't input-seek straight to the target — the
            # ``subtitles`` filter would render nothing because libass
            # needs to observe at least a brief window of frames with
            # PTS leading up to the seek point before it starts
            # emitting glyphs. Land the input demuxer slightly earlier
            # and let the output-side seek discard the warmup frames so
            # the playlist position stays exact.
            command.extend(["-ss", f"{seek_seconds}", "-copyts"])
        command.extend(["-i", source_path, "-avoid_negative_ts", "make_zero"])
        keyframe_expr = (
            f"expr:gte(t,{seek_seconds}+n_forced*{segment_seconds})"
            if seek_seconds > 0
            else f"expr:gte(t,n_forced*{segment_seconds})"
        )
        command.extend(["-map", "0:v:0"])
        if audio_track is None:
            command.extend(["-map", "0:a:0?"])
        else:
            command.extend(["-map", f"0:a:{max(0, int(audio_track))}?"])
        # ``-force_key_frames`` guarantees a key-frame at every segment
        # boundary so the resulting .ts files are independently
        # decodable, which HLS requires for arbitrary seeking.
        command.extend(
            [
                "-c:v",
                "libx264",
                # Keep H.264 output inside the broadest browser-decoder
                # compatibility envelope. Some sources are 10-bit /
                # 4:4:4 and libx264 mirrors that by default, which can
                # make MediaSource append throw in Chromium.
                "-pix_fmt",
                "yuv420p",
                "-profile:v",
                "high",
                "-level:v",
                "4.1",
                "-preset",
                "veryfast",
                "-crf",
                "23",
                "-force_key_frames",
                keyframe_expr,
                "-c:a",
                "aac",
                "-ar",
                "48000",
                "-ac",
                "2",
                "-b:a",
                "160k",
                "-max_muxing_queue_size",
                "1024",
                "-f",
                "hls",
                "-hls_time",
                str(segment_seconds),
                "-hls_playlist_type",
                "event",
                "-hls_list_size",
                "0",
                # ``append_list`` would tell ffmpeg to keep merging
                # into any existing playlist file, which conflicts
                # with us recycling the same output directory across
                # seek-on-demand restarts. ``temp_file`` makes ffmpeg
                # write to ``segment_NNNNN.ts.tmp`` and rename on
                # completion so we never observe a partial segment.
                "-hls_flags",
                "independent_segments+temp_file",
                "-hls_segment_type",
                "mpegts",
                "-hls_segment_filename",
                segment_pattern,
                "-start_number",
                str(start_segment_index),
                playlist_output,
            ]
        )
        return command

    def _wait_for_initial_manifest(
        self,
        *,
        session_id: str,
        process: subprocess.Popen[bytes],
        manifest_path: str,
    ) -> None:
        """Legacy startup path used when the caller did not pre-write
        a VOD playlist. We block until ffmpeg produces ``index.m3u8``
        so the client has something to load. The ``_spawn_with_…``
        helper has already verified that the process is alive past
        its early-death window, so here we only need to wait."""
        deadline = time.time() + self._startup_timeout_seconds
        while time.time() < deadline:
            if os.path.isfile(manifest_path):
                return
            if process.poll() is not None:
                with self._lock:
                    self._active.pop(session_id, None)
                _LOG.warning("transcode_failed_early session=%s", session_id)
                raise InfrastructureError(
                    "Transcoder exited before playlist became ready."
                )
            time.sleep(0.2)

    def materialize_subtitle_tracks(
        self,
        *,
        source_path: str,
        output_dir: str,
    ) -> list[dict[str, object]]:
        """Extract text subtitle tracks as WebVTT sidecars.

        For SSA/ASS (``codec_name`` of ``ass`` or ``ssa``), also writes a
        ``.ass`` sidecar (stream copy) for high-fidelity browser rendering
        via libass (see web player).

        Returned entries have ``id``/``label``/``codec`` matching
        ``probe_media_tracks`` plus ``filename`` (WebVTT) and optional
        ``ass_filename`` for files written under ``output_dir``.
        """
        ffmpeg_cmd = shutil.which(self._ffmpeg_bin) or self._ffmpeg_bin
        tracks = self.probe_media_tracks(source_path).get("subtitles", [])
        out: list[dict[str, object]] = []
        for track in tracks:
            try:
                sub_id = max(0, int(track.get("id")))  # type: ignore[arg-type]
            except (TypeError, ValueError):
                continue
            codec = str(track.get("codec") or "").strip().lower()
            filename = f"subtitle_{sub_id:03d}.vtt"
            target = str(Path(output_dir) / filename)
            command = [
                ffmpeg_cmd,
                "-hide_banner",
                "-loglevel",
                "error",
                "-nostdin",
                "-y",
                "-i",
                source_path,
                "-map",
                f"0:s:{sub_id}?",
                "-f",
                "webvtt",
                target,
            ]
            try:
                subprocess.run(
                    command,
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=30,
                )
            except Exception:
                continue
            if not os.path.isfile(target):
                continue
            row: dict[str, object] = {
                "id": sub_id,
                "label": str(track.get("label") or f"Subtitle {sub_id}"),
                "filename": filename,
                "codec": codec,
            }
            if codec in ("ass", "ssa"):
                ass_name = f"subtitle_{sub_id:03d}.ass"
                ass_target = str(Path(output_dir) / ass_name)
                ass_cmd = [
                    ffmpeg_cmd,
                    "-hide_banner",
                    "-loglevel",
                    "error",
                    "-nostdin",
                    "-y",
                    "-i",
                    source_path,
                    "-map",
                    f"0:s:{sub_id}?",
                    "-c",
                    "copy",
                    ass_target,
                ]
                try:
                    subprocess.run(
                        ass_cmd,
                        check=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                        timeout=30,
                    )
                except Exception:
                    pass
                if os.path.isfile(ass_target) and os.path.getsize(ass_target) > 0:
                    row["ass_filename"] = ass_name
            out.append(row)
        return out

    @staticmethod
    def _write_spawn_record(log_path: str, command: list[str]) -> None:
        try:
            with open(log_path, "ab") as fh:
                stamp = time.strftime("%Y-%m-%d %H:%M:%S")
                fh.write(
                    f"\n[AnimeManager] ffmpeg spawn {stamp}\n{' '.join(command)}\n".encode(
                        "utf-8",
                        errors="replace",
                    )
                )
        except OSError:
            pass

    def _spawn_ffmpeg(
        self,
        command: list[str],
        log_path: str,
    ) -> subprocess.Popen[bytes]:
        # Mirror stderr to a per-session log file so failures (subtitle
        # filter errors, unreadable input, codec issues) leave a
        # forensic trail under the session's output directory. We open
        # in append-binary mode and immediately close our handle —
        # ``subprocess.Popen`` keeps its own dup of the file descriptor
        # for the lifetime of the child.
        log_file = open(log_path, "ab")
        try:
            return subprocess.Popen(
                command,
                stdout=subprocess.DEVNULL,
                stderr=log_file,
            )
        finally:
            log_file.close()

    @staticmethod
    def _purge_ts_segments(output_dir: str) -> None:
        """Remove completed ``segment_*.ts`` files before an incompatible
        ffmpeg restart. See :meth:`ensure_hls_session` for when this runs."""
        try:
            for entry in os.listdir(output_dir):
                if not entry.startswith("segment_") or not entry.endswith(".ts"):
                    continue
                try:
                    os.remove(str(Path(output_dir) / entry))
                except OSError:
                    pass
        except FileNotFoundError:
            pass

    @staticmethod
    def _clear_stale_ffmpeg_artifacts(*, ffmpeg_playlist: str, output_dir: str) -> None:
        """Remove leftovers from a previous ffmpeg run so the new
        process starts from a known-clean state. We deliberately do
        *not* touch ``index.m3u8`` (that's the canonical playlist the
        application layer owns) or the produced ``segment_NNNNN.ts``
        files (those remain valid across restarts because PTS values
        are kept aligned with the playlist by ``-copyts``)."""
        try:
            os.remove(ffmpeg_playlist)
        except FileNotFoundError:
            pass
        except OSError as exc:
            _LOG.debug("ffmpeg_playlist_unlink_failed path=%s err=%s", ffmpeg_playlist, exc)
        # Stray ``segment_NNNNN.ts.tmp`` files from a hard kill of a
        # previous process can confuse the new ffmpeg's atomic rename.
        try:
            for entry in os.listdir(output_dir):
                if entry.endswith(".ts.tmp"):
                    try:
                        os.remove(str(Path(output_dir) / entry))
                    except OSError:
                        pass
        except FileNotFoundError:
            pass

    def _terminate(self, process: subprocess.Popen[bytes]) -> None:
        if process.poll() is not None:
            return
        try:
            process.terminate()
            process.wait(timeout=3)
        except Exception:
            try:
                process.kill()
                process.wait(timeout=1)
            except Exception:
                pass


__all__ = ["FFmpegTranscoderAdapter"]
