"""FFmpeg-backed HLS transcoder adapter.

The adapter spins up one ffmpeg process per playback session. Encoding
runs in the background and writes MPEG-TS segments named
``segment_NNNNN.ts`` to the session's output directory. The HLS
playlist that the *client* consumes (``index.m3u8``) is pre-written by
the application layer once the source's total duration is known — we
deliberately have ffmpeg write its own playlist to a sentinel file
(``_ffmpeg.m3u8``) and ignore it so we can support arbitrary seeking
without the playlist growing piecewise.

To make user seeks land instantly, the application layer can call
:meth:`ensure_hls_session` again with ``start_segment_index=N``. We
then terminate the current ffmpeg process and spawn a new one that
input-seeks to ``N * segment_seconds`` and resumes segment numbering at
``N``. ``-copyts`` keeps PTS continuous with the canonical playlist so
the player can splice from any previous segment to the new ones
without an ``#EXT-X-DISCONTINUITY`` marker.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import threading
import time
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path

from domain.errors import InfrastructureError

_LOG = logging.getLogger(__name__)


@dataclass(slots=True)
class _ActiveTranscode:
    session_id: str
    output_dir: str
    manifest_path: str
    process: subprocess.Popen[bytes]
    started_at: float
    start_segment_index: int
    segment_seconds: int
    source_path: str
    audio_track: int | None
    subtitle_track: int | None


class FFmpegTranscoderAdapter:
    """Materialize HLS artifacts using one ffmpeg process per session."""

    # ffmpeg writes its own playlist to this name inside the session
    # directory. We never serve this file; the canonical playlist that
    # the client receives (``index.m3u8``) is generated by the
    # application layer once the source duration is known.
    _FFMPEG_PLAYLIST_NAME = "_ffmpeg.m3u8"
    # Per-session ffmpeg stderr is mirrored here so a failed transcode
    # leaves behind a forensic trail without polluting the process
    # stdout. The file is opened in append mode; restarts share it.
    _FFMPEG_LOG_NAME = "_ffmpeg.log"

    def __init__(
        self,
        *,
        ffmpeg_bin: str = "ffmpeg",
        ffprobe_bin: str = "ffprobe",
        video_codec: str = "libx264",
        require_hardware_acceleration: bool = False,
        use_cuda_hwaccel: bool = False,
        max_active_sessions: int = 2,
        segment_seconds: int = 4,
        startup_timeout_seconds: int = 15,
    ) -> None:
        self._ffmpeg_bin = ffmpeg_bin
        self._ffprobe_bin = ffprobe_bin
        self._video_codec = str(video_codec or "libx264").strip().lower()
        self._require_hardware_acceleration = bool(require_hardware_acceleration)
        self._use_cuda_hwaccel = bool(use_cuda_hwaccel)
        self._max_active_sessions = max(1, int(max_active_sessions))
        self._segment_seconds = max(2, int(segment_seconds))
        self._startup_timeout_seconds = max(3, int(startup_timeout_seconds))
        self._active: dict[str, _ActiveTranscode] = {}
        self._lock = threading.RLock()
        self._nvenc_validated = False
        self._probe_memo_lock = threading.Lock()
        self._probe_memo: OrderedDict[
            str, tuple[dict[str, list[dict[str, object]]], float]
        ] = OrderedDict()
        self._probe_memo_max = 64

    # ------------------------------------------------------------------
    # MediaTranscoderPort
    # ------------------------------------------------------------------

    def ensure_hls_session(
        self,
        *,
        session_id: str,
        source_path: str,
        output_dir: str,
        audio_track: int | None = None,
        subtitle_track: int | None = None,
        start_segment_index: int = 0,
        segment_seconds: int | None = None,
    ) -> dict[str, str]:
        ffmpeg_cmd = shutil.which(self._ffmpeg_bin) or self._ffmpeg_bin
        seg_secs = (
            int(segment_seconds)
            if segment_seconds is not None
            else self._segment_seconds
        )
        seg_secs = max(2, seg_secs)
        start_index = max(0, int(start_segment_index))
        manifest_path = str(Path(output_dir) / "index.m3u8")
        ffmpeg_playlist = str(Path(output_dir) / self._FFMPEG_PLAYLIST_NAME)
        # When the application layer has pre-written ``index.m3u8`` we
        # must not let ffmpeg touch it — its hls muxer would clobber
        # the carefully-crafted full segment list. We also need to
        # avoid the canonical playlist whenever we're restarting mid-
        # stream (``start_index > 0``). Everything else (the original
        # "live" code path where nobody pre-wrote a manifest) keeps
        # the legacy behaviour: ffmpeg owns ``index.m3u8`` directly.
        caller_owns_playlist = os.path.isfile(manifest_path) or start_index > 0
        ffmpeg_target_playlist = (
            ffmpeg_playlist if caller_owns_playlist else manifest_path
        )

        with self._lock:
            self._reap_finished_locked()
            self._validate_required_acceleration(ffmpeg_cmd)
            existing = self._active.get(session_id)
            if (
                existing is not None
                and existing.process.poll() is None
                and existing.start_segment_index == start_index
                and existing.segment_seconds == seg_secs
                and existing.audio_track == audio_track
            ):
                return {
                    "manifest_path": existing.manifest_path,
                    "output_dir": existing.output_dir,
                    "start_segment_index": str(existing.start_segment_index),
                    "segment_seconds": str(existing.segment_seconds),
                }
            # Tear down a divergent process before launching a new one
            # so that two ffmpeg instances don't fight over the same
            # output directory. This is what makes "seek beyond the
            # current encode head" possible.
            purge_segments = False
            if existing is not None:
                # A later encode that started further into the file leaves
                # ``segment_NNNNN.ts`` files whose timestamps align with that
                # offset. If we restart ffmpeg *earlier* (common when the
                # player prefetches segment 0 while the session was started
                # mid-file from a resume hint), those high-index segments
                # become stale: their PTS no longer matches the new low
                # segments and Shaka aborts with a generic decode error.
                # Different audio or segment length also invalidates every
                # existing transport stream.
                if (
                    start_index < existing.start_segment_index
                    or audio_track != existing.audio_track
                    or seg_secs != existing.segment_seconds
                ):
                    purge_segments = True
                self._terminate(existing.process)
                self._active.pop(session_id, None)
            if len(self._active) >= self._max_active_sessions:
                raise InfrastructureError(
                    "Media server is busy: too many active transcoding sessions."
                )

            os.makedirs(output_dir, exist_ok=True)
            if purge_segments:
                self._purge_ts_segments(output_dir)
            # The HLS muxer's ``append_list`` flag refuses to truncate
            # an existing playlist file, which on a seek-on-demand
            # restart leaves behind stale entries from the previous
            # encode. Removing the sentinel up front gives ffmpeg a
            # clean slate and avoids the muxer hanging while trying
            # to merge incompatible playlist states.
            self._clear_stale_ffmpeg_artifacts(
                ffmpeg_playlist=ffmpeg_playlist,
                output_dir=output_dir,
            )
            log_path = str(Path(output_dir) / self._FFMPEG_LOG_NAME)
            command = self._build_command(
                ffmpeg_cmd=ffmpeg_cmd,
                source_path=source_path,
                playlist_output=ffmpeg_target_playlist,
                output_dir=output_dir,
                audio_track=audio_track,
                subtitle_track=subtitle_track,
                start_segment_index=start_index,
                segment_seconds=seg_secs,
            )
            _LOG.info(
                "ffmpeg_spawn source=%s start_seg=%s audio=%s subtitle=%s cmd=%s",
                source_path,
                start_index,
                audio_track,
                subtitle_track,
                " ".join(command),
            )
            process = self._spawn_ffmpeg(command, log_path)
            self._active[session_id] = _ActiveTranscode(
                session_id=session_id,
                output_dir=output_dir,
                manifest_path=manifest_path,
                process=process,
                started_at=time.time(),
                start_segment_index=start_index,
                segment_seconds=seg_secs,
                source_path=source_path,
                audio_track=audio_track,
                subtitle_track=None,
            )
            _LOG.info(
                "transcode_started session=%s active=%s source=%s start_seg=%s subs=%s log=%s",
                session_id,
                len(self._active),
                source_path,
                start_index,
                None,
                log_path,
            )

        # If the application layer pre-wrote ``index.m3u8`` we can
        # return immediately — the client only needs the manifest,
        # not the first segment. Otherwise, we keep the legacy
        # behaviour of blocking until ffmpeg has produced ``index.m3u8``
        # so the client has something to load.
        if not os.path.isfile(manifest_path):
            self._wait_for_initial_manifest(
                session_id=session_id,
                process=process,
                manifest_path=manifest_path,
            )

        return {
            "manifest_path": manifest_path,
            "output_dir": output_dir,
            "start_segment_index": str(start_index),
            "segment_seconds": str(seg_secs),
            "log_path": log_path,
            "effective_subtitle_track": "",
        }

    def stop_hls_session(self, session_id: str) -> None:
        with self._lock:
            active = self._active.pop(session_id, None)
        if active is None:
            return
        self._terminate(active.process)
        _LOG.info("transcode_stopped session=%s", session_id)

    @staticmethod
    def _as_probe_float(value: object) -> float:
        try:
            f = float(value)  # type: ignore[arg-type]
        except (TypeError, ValueError):
            return 0.0
        if f != f:  # NaN guard
            return 0.0
        return max(0.0, f)

    @staticmethod
    def _parse_probe_streams(payload: dict[str, object]) -> dict[str, list[dict[str, object]]]:
        streams = list(payload.get("streams") or [])
        audio: list[dict[str, object]] = []
        subtitles: list[dict[str, object]] = []
        audio_pos = 0
        sub_pos = 0
        for stream in streams:
            kind = str(stream.get("codec_type") or "")
            tags = stream.get("tags") or {}
            if not isinstance(tags, dict):
                tags = {}
            if not isinstance(tags, dict):
                tags = {}
            lang = str(tags.get("language") or "und")
            title = str(tags.get("title") or "").strip()
            label = f"{lang.upper()}"
            if title:
                label = f"{label} · {title}"
            if kind == "audio":
                audio.append({"id": audio_pos, "label": label})
                audio_pos += 1
            elif kind == "subtitle":
                codec_raw = str(stream.get("codec_name") or "").strip().lower()
                subtitles.append({"id": sub_pos, "label": label, "codec": codec_raw})
                sub_pos += 1
        return {"audio": audio, "subtitles": subtitles}

    @classmethod
    def _duration_from_probe_payload(cls, payload: dict[str, object]) -> float:
        fmt_dur = cls._as_probe_float((payload.get("format") or {}).get("duration"))
        if fmt_dur > 0:
            return fmt_dur
        stream_durations = [
            cls._as_probe_float(stream.get("duration"))
            for stream in (payload.get("streams") or [])
        ]
        return max(stream_durations, default=0.0)

    def _probe_fingerprint(self, source_path: str) -> str | None:
        try:
            st = os.stat(source_path)
            real = os.path.realpath(source_path)
            return f"{real}\0{st.st_mtime_ns}\0{st.st_size}"
        except OSError:
            return None

    def _probe_media_combined_uncached(
        self, source_path: str
    ) -> tuple[dict[str, list[dict[str, object]]], float]:
        ffprobe_cmd = shutil.which(self._ffprobe_bin) or self._ffprobe_bin
        command = [
            ffprobe_cmd,
            "-v",
            "error",
            "-show_entries",
            "format=duration:stream=index,codec_type,codec_name,duration:stream_tags=language,title",
            "-of",
            "json",
            source_path,
        ]
        try:
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
                timeout=15,
            )
            payload = json.loads(result.stdout or "{}")
        except Exception:
            return {"audio": [], "subtitles": []}, 0.0
        if not isinstance(payload, dict):
            return {"audio": [], "subtitles": []}, 0.0
        tracks = self._parse_probe_streams(payload)
        duration = self._duration_from_probe_payload(payload)
        return tracks, duration

    def probe_media_metadata(
        self, source_path: str
    ) -> tuple[dict[str, list[dict[str, object]]], float]:
        """Single ffprobe run: audio/subtitle tracks plus duration in seconds."""
        fp = self._probe_fingerprint(source_path)
        with self._probe_memo_lock:
            if fp and fp in self._probe_memo:
                self._probe_memo.move_to_end(fp)
                return self._probe_memo[fp]
        tracks, duration = self._probe_media_combined_uncached(source_path)
        if fp:
            with self._probe_memo_lock:
                self._probe_memo[fp] = (tracks, duration)
                self._probe_memo.move_to_end(fp)
                while len(self._probe_memo) > self._probe_memo_max:
                    self._probe_memo.popitem(last=False)
        return tracks, duration

    def probe_media_tracks(self, source_path: str) -> dict[str, list[dict[str, object]]]:
        return self.probe_media_metadata(source_path)[0]

    def probe_media_duration(self, source_path: str) -> float:
        """Return the duration of ``source_path`` in seconds.

        We try the container-level ``format=duration`` first, then fall
        back to the longest stream duration. Returns ``0.0`` when the
        duration is not available — the caller is expected to drop back
        to a live-style playlist when that happens.
        """
        return self.probe_media_metadata(source_path)[1]

    # ------------------------------------------------------------------
    # Implementation details
    # ------------------------------------------------------------------

    def _reap_finished_locked(self) -> None:
        for session_id, active in list(self._active.items()):
            if active.process.poll() is not None:
                self._active.pop(session_id, None)

    def _build_command(
        self,
        *,
        ffmpeg_cmd: str,
        source_path: str,
        playlist_output: str,
        output_dir: str,
        audio_track: int | None,
        subtitle_track: int | None,
        start_segment_index: int,
        segment_seconds: int,
    ) -> list[str]:
        segment_pattern = str(Path(output_dir) / "segment_%05d.ts")
        # Input-seek to N*seg_secs so that ffmpeg's first emitted segment
        # corresponds to the requested playlist position. ``-copyts``
        # keeps PTS values aligned with the canonical playlist time so
        # the player can splice from any previous segment to the new
        # ones without an ``#EXT-X-DISCONTINUITY`` marker.
        seek_seconds = start_segment_index * segment_seconds
        command: list[str] = [ffmpeg_cmd, "-hide_banner", "-loglevel", "error", "-nostdin", "-y"]
        if seek_seconds > 0:
            # Input-side ``-ss`` is fast but keyframe-granular: ffmpeg
            # often lands a little *before* ``seek_seconds``. With
            # ``-copyts`` that drift propagates directly into the .ts
            # timestamps, so a restarted encoder can write
            # ``segment_NNNNN.ts`` whose payload actually belongs to an
            # earlier timeline region than NNNNN. Pairing fast input
            # seek with a precise output-side ``-ss`` re-trim keeps
            # segment indices and media timestamps aligned after skips.
            command.extend(["-ss", f"{seek_seconds}", "-copyts"])
        if self._using_nvenc() and self._use_cuda_hwaccel:
            command.extend(["-hwaccel", "cuda", "-hwaccel_output_format", "cuda"])
        command.extend(["-i", source_path])
        if seek_seconds > 0:
            # Output-side seek is precise (decode-and-discard) and with
            # ``-copyts`` uses the original timeline, so this must be
            # the absolute target timestamp.
            command.extend(["-ss", f"{seek_seconds}"])
        command.extend(["-map", "0:v:0"])
        if audio_track is None:
            command.extend(["-map", "0:a:0?"])
        else:
            command.extend(["-map", f"0:a:{max(0, int(audio_track))}?"])
        # ``-force_key_frames`` guarantees a key-frame at every segment
        # boundary so the resulting .ts files are independently
        # decodable, which HLS requires for arbitrary seeking.
        command.extend(
            [
                *self._video_flags(segment_seconds),
                "-c:a",
                "aac",
                "-b:a",
                "160k",
                "-f",
                "hls",
                "-hls_time",
                str(segment_seconds),
                "-hls_playlist_type",
                "event",
                "-hls_list_size",
                "0",
                # ``append_list`` would tell ffmpeg to keep merging
                # into any existing playlist file, which conflicts
                # with us recycling the same output directory across
                # seek-on-demand restarts. ``temp_file`` makes ffmpeg
                # write to ``segment_NNNNN.ts.tmp`` and rename on
                # completion so we never observe a partial segment.
                "-hls_flags",
                "independent_segments+temp_file",
                "-hls_segment_type",
                "mpegts",
                "-hls_segment_filename",
                segment_pattern,
                "-start_number",
                str(start_segment_index),
                playlist_output,
            ]
        )
        return command

    def _using_nvenc(self) -> bool:
        return self._video_codec == "h264_nvenc"

    def _video_flags(self, segment_seconds: int) -> list[str]:
        keyframe_expr = f"expr:gte(t,n_forced*{segment_seconds})"
        if self._using_nvenc():
            # ``-b:v 0`` + CQ keeps quality-driven output similar to CRF
            # while still using NVENC's hardware encoder.
            return [
                "-c:v",
                "h264_nvenc",
                "-pix_fmt",
                "yuv420p",
                "-profile:v",
                "high",
                "-level:v",
                "4.1",
                "-preset",
                "p5",
                "-tune",
                "hq",
                "-rc:v",
                "vbr",
                "-cq:v",
                "23",
                "-b:v",
                "0",
                "-force_key_frames",
                keyframe_expr,
            ]
        # Keep H.264 output inside the broadest browser-decoder
        # compatibility envelope. Some sources are 10-bit / 4:4:4 and
        # libx264 mirrors that by default, which can make MediaSource
        # append throw in Chromium.
        return [
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-profile:v",
            "high",
            "-level:v",
            "4.1",
            "-preset",
            "veryfast",
            "-crf",
            "23",
            "-force_key_frames",
            keyframe_expr,
        ]

    def _validate_required_acceleration(self, ffmpeg_cmd: str) -> None:
        if not self._require_hardware_acceleration:
            return
        if not self._using_nvenc():
            raise InfrastructureError(
                "Hardware acceleration is required, but the configured video codec is not NVIDIA NVENC."
            )
        if self._nvenc_validated:
            return
        try:
            encoders = subprocess.run(
                [ffmpeg_cmd, "-hide_banner", "-loglevel", "error", "-encoders"],
                check=True,
                capture_output=True,
                text=True,
                timeout=10,
            )
        except Exception as exc:  # noqa: BLE001
            raise InfrastructureError(
                f"NVIDIA GPU acceleration is required but ffmpeg encoder discovery failed: {exc}"
            ) from exc
        if "h264_nvenc" not in (encoders.stdout or ""):
            raise InfrastructureError(
                "NVIDIA GPU acceleration is required but ffmpeg does not expose the h264_nvenc encoder."
            )
        probe_command = [
            ffmpeg_cmd,
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            # Some NVIDIA drivers reject very small frame sizes during
            # encoder init even though they're valid in theory. Use a
            # conservative HD probe frame to avoid false negatives.
            "nullsrc=size=1280x720:rate=1",
            "-frames:v",
            "1",
            "-c:v",
            "h264_nvenc",
            "-f",
            "null",
            "-",
        ]
        try:
            subprocess.run(
                probe_command,
                check=True,
                capture_output=True,
                text=True,
                timeout=15,
            )
        except Exception as exc:  # noqa: BLE001
            detail = ""
            if isinstance(exc, subprocess.CalledProcessError):
                detail = (exc.stderr or exc.stdout or "").strip()
            if not detail:
                detail = str(exc)
            raise InfrastructureError(
                "NVIDIA GPU acceleration is required but a test NVENC encode failed. "
                f"ffmpeg output: {detail}"
            ) from exc
        self._nvenc_validated = True

    def _wait_for_initial_manifest(
        self,
        *,
        session_id: str,
        process: subprocess.Popen[bytes],
        manifest_path: str,
    ) -> None:
        """Legacy startup path used when the caller did not pre-write
        a VOD playlist. We block until ffmpeg produces ``index.m3u8``
        so the client has something to load. The ``_spawn_with_…``
        helper has already verified that the process is alive past
        its early-death window, so here we only need to wait."""
        deadline = time.time() + self._startup_timeout_seconds
        while time.time() < deadline:
            if os.path.isfile(manifest_path):
                return
            if process.poll() is not None:
                with self._lock:
                    self._active.pop(session_id, None)
                _LOG.warning("transcode_failed_early session=%s", session_id)
                raise InfrastructureError(
                    "Transcoder exited before playlist became ready."
                )
            time.sleep(0.2)

    def materialize_subtitle_tracks(
        self,
        *,
        source_path: str,
        output_dir: str,
    ) -> list[dict[str, object]]:
        """Extract text subtitle tracks as WebVTT sidecars.

        For SSA/ASS (``codec_name`` of ``ass`` or ``ssa``), also writes a
        ``.ass`` sidecar (stream copy) for high-fidelity browser rendering
        via libass (see web player).

        Returned entries have ``id``/``label``/``codec`` matching
        ``probe_media_tracks`` plus ``filename`` (WebVTT) and optional
        ``ass_filename`` for files written under ``output_dir``.
        """
        ffmpeg_cmd = shutil.which(self._ffmpeg_bin) or self._ffmpeg_bin
        tracks = self.probe_media_tracks(source_path).get("subtitles", [])
        out: list[dict[str, object]] = []
        for track in tracks:
            try:
                sub_id = max(0, int(track.get("id")))  # type: ignore[arg-type]
            except (TypeError, ValueError):
                continue
            codec = str(track.get("codec") or "").strip().lower()
            filename = f"subtitle_{sub_id:03d}.vtt"
            target = str(Path(output_dir) / filename)
            command = [
                ffmpeg_cmd,
                "-hide_banner",
                "-loglevel",
                "error",
                "-nostdin",
                "-y",
                "-i",
                source_path,
                "-map",
                f"0:s:{sub_id}?",
                "-f",
                "webvtt",
                target,
            ]
            try:
                subprocess.run(
                    command,
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=30,
                )
            except Exception:
                continue
            if not os.path.isfile(target):
                continue
            row: dict[str, object] = {
                "id": sub_id,
                "label": str(track.get("label") or f"Subtitle {sub_id}"),
                "filename": filename,
                "codec": codec,
            }
            if codec in ("ass", "ssa"):
                ass_name = f"subtitle_{sub_id:03d}.ass"
                ass_target = str(Path(output_dir) / ass_name)
                ass_cmd = [
                    ffmpeg_cmd,
                    "-hide_banner",
                    "-loglevel",
                    "error",
                    "-nostdin",
                    "-y",
                    "-i",
                    source_path,
                    "-map",
                    f"0:s:{sub_id}?",
                    "-c",
                    "copy",
                    ass_target,
                ]
                try:
                    subprocess.run(
                        ass_cmd,
                        check=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                        timeout=30,
                    )
                except Exception:
                    pass
                if os.path.isfile(ass_target) and os.path.getsize(ass_target) > 0:
                    row["ass_filename"] = ass_name
            out.append(row)
        return out

    def _spawn_ffmpeg(
        self,
        command: list[str],
        log_path: str,
    ) -> subprocess.Popen[bytes]:
        # Mirror stderr to a per-session log file so failures (subtitle
        # filter errors, unreadable input, codec issues) leave a
        # forensic trail under the session's output directory. We open
        # in append-binary mode and immediately close our handle —
        # ``subprocess.Popen`` keeps its own dup of the file descriptor
        # for the lifetime of the child.
        log_file = open(log_path, "ab")
        try:
            return subprocess.Popen(
                command,
                stdout=subprocess.DEVNULL,
                stderr=log_file,
            )
        finally:
            log_file.close()

    @staticmethod
    def _purge_ts_segments(output_dir: str) -> None:
        """Remove completed ``segment_*.ts`` files before an incompatible
        ffmpeg restart. See :meth:`ensure_hls_session` for when this runs."""
        try:
            for entry in os.listdir(output_dir):
                if not entry.startswith("segment_") or not entry.endswith(".ts"):
                    continue
                try:
                    os.remove(str(Path(output_dir) / entry))
                except OSError:
                    pass
        except FileNotFoundError:
            pass

    @staticmethod
    def _clear_stale_ffmpeg_artifacts(*, ffmpeg_playlist: str, output_dir: str) -> None:
        """Remove leftovers from a previous ffmpeg run so the new
        process starts from a known-clean state. We deliberately do
        *not* touch ``index.m3u8`` (that's the canonical playlist the
        application layer owns) or the produced ``segment_NNNNN.ts``
        files (those remain valid across restarts because PTS values
        are kept aligned with the playlist by ``-copyts``)."""
        try:
            os.remove(ffmpeg_playlist)
        except FileNotFoundError:
            pass
        except OSError as exc:
            _LOG.debug("ffmpeg_playlist_unlink_failed path=%s err=%s", ffmpeg_playlist, exc)
        # Stray ``segment_NNNNN.ts.tmp`` files from a hard kill of a
        # previous process can confuse the new ffmpeg's atomic rename.
        try:
            for entry in os.listdir(output_dir):
                if entry.endswith(".ts.tmp"):
                    try:
                        os.remove(str(Path(output_dir) / entry))
                    except OSError:
                        pass
        except FileNotFoundError:
            pass

    def _terminate(self, process: subprocess.Popen[bytes]) -> None:
        if process.poll() is not None:
            return
        try:
            process.terminate()
            process.wait(timeout=3)
        except Exception:
            try:
                process.kill()
                process.wait(timeout=1)
            except Exception:
                pass


__all__ = ["FFmpegTranscoderAdapter"]
